# Istio/default — discovery selectors + OTLP tracing to otel-collector.
apiVersion: sailoperator.io/v1
kind: Istio
metadata:
  name: default
spec:
  namespace: maurizio-istio-system
  version: v1.27-latest
  values:
    meshConfig:
      discoverySelectors:
        - matchLabels:
            istio-discovery: enabled
      enableTracing: true
      extensionProviders:
        - name: otel
          opentelemetry:
            service: otel-collector.maurizio-istio-system.svc.cluster.local
            port: 4317
