# Scrape istiod control plane metrics (OpenShift user workload monitoring).
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istiod-monitor
  namespace: maurizio-istio-system
spec:
  endpoints:
    - interval: 30s
      port: http-monitoring
  selector:
    matchLabels:
      app: istiod
  targetLabels:
    - app
