# Mesh-wide metrics and tracing (OTLP via extension provider otel).
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: default
  namespace: maurizio-istio-system
spec:
  metrics:
    - providers:
        - name: prometheus
  tracing:
    - providers:
        - name: otel
      randomSamplingPercentage: 100
